version: "3"

#src pihole: https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:

  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:arm
    hostname: cloudflared
    cap_add:
      - NET_ADMIN
    restart: always
    environment:
      - "TZ=Europe/Paris"
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
    networks:
      webgateway:
        ipv4_address: 172.20.0.20

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole 
    networks:
      webgateway: 
        ipv4_address: 172.20.0.10
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - "TZ=Europe/Paris"
      - "ServerIP=172.20.0.10" 
      - "PROXY_LOCATION=pihole"
      - "VIRTUAL_PORT=80"
      - "DNS1=172.20.0.20#5054"
      - "DNS2=1.1.1.1"
      - "IPv6=false"
      - DNSMASQ_LISTENING=all
      #- WEBPASSWORD=admin
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './config/etc-pihole/:/etc/pihole/'
      - './config/etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    # Add your own custom hostnames you need for your domain
    #extra_hosts:
    #  - 'loki.eniac.local:192.168.0.100'
    dns:
      - 127.0.0.1
    #  - 192.168.0.100
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: always

networks:
  webgateway:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24 
